name: Sync tags

on:
  pull_request:
    paths:
      - "sync_tags.py"
      - "github_utils.py"
      - ".github/workflows/sync-tags.yml"

  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  sync_tags_dry_run:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.x

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install dependencies
        run: |
          uv sync

      - name: Run sync in dry-run mode
        run: |
          uv run python sync_tags.py --dry-run

      - name: Run unit tests
        run: |
          uv run python -m unittest discover -s tests -p "test_*.py"

  sync_tags:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.x

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install dependencies
        run: |
          uv sync

      - name: Sync tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run python sync_tags.py
